package getajob.pymes.freelancepymes.marketplace.enums;

public enum ProjectCategory {
    DESARROLLO_WEB,
    DESARROLLO_MOVIL,
    DISENO_GRAFICO,
    MARKETING_DIGITAL,
    CONTABILIDAD,
    CONSULTORIA,
    TRADUCCION,
    REDACCION,
    OTROS,
    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    GRAPHIC_DESIGN,
    DIGITAL_MARKETING,
    ACCOUNTING,
    CONSULTING,
    TRANSLATION,
    WRITING,
    OTHER
}
