paypal:
  client-id: AU7MKeI9zrkyXm8t_iHwQbR85Z6wUEQKJw5gJbe_ylMsuHgw4cL9XByjF9w5noc9XbBxVrdVDsyWAy_N
  client-secret: EN8ICxlx_lHw-5VWYWTRxKOiZYFJX5tref9jUEsL22YGjCjnzEOiloD3F-wEJ9LckaeIIm6icAK-hDGS
  mode: sandbox

cloudflare:
  r2:
    endpoint: https://7649d11884d4e4cdbd2ac86deb11486e.r2.cloudflarestorage.com
    bucket: pymes
    access-key: 33d76a66f9273df33c54891e2dc00bc6
    secret-key: 73aeeadd1a2e22441e4f4bf4f0e5da4ae8425b2ae359abf293104ce1047b65b9
spring:
    profiles:
        active: local

    datasource:
        url: jdbc:postgresql://${PGHOST:localhost}:5432/${PGDATABASE:freelancepymes_db}?sslmode=${PGSSLMODE:disable}
        username: ${PGUSER:postgres}
        password: ${PGPASSWORD:admin}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
do:
  spaces:
    endpoint: https://sfo3.digitaloceanspaces.com
    bucket: tu-nombre-de-bucket
    access-key: ${DO_ACCESS_KEY:mock_access_key}
    secret-key: ${DO_SECRET_KEY:mock_secret_key}
app:
  jwt:
    secret: 9a4f2c8d3b7a1e5f8g9h0i1j2k3l4m5n6o7p8q9r0s1t2u3v4w5x6y7z8a9b0c1d
    expiration-ms: 86400000
  oauth2:
    google:
      client-id: ${GOOGLE_CLIENT_ID:mock_google_client_id}
  ai:
    fastapi-url: ${FASTAPI_URL:http://localhost:8000}
